### ISSUE TITLE
Add details about usage in readme.md

### ISSUE THREAD

**Issue by richardjr** [nautoguide/nautoguide-apipush#2]
Can you add the usage instructions into the readme.md.

Then as a test lets get geovey public working with this. So start by copying a few of the simple reports over into an SQL and then update it using this tool. If that works then lets get the entire of geovey_public and also OS over into their own repos.

That way both those projects are totally off the legacy system.

**Comment by citizenfish** [comment]
I will do the reports SQL as I've converted Geovey to JSONB
